trigger:
  tags:
    include:
    - v*

pr: none

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install pytest pytest-cov twine wheel
    pip install -e .
  displayName: 'Install dependencies'

- script: |
    pytest tests/ --junitxml=junit/test-results.xml --cov=nitdms --cov-report=html --cov-report=xml
  displayName: 'Run test suite'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/test-*.xml'
    testRunTitle: 'Test results for Python $(python.version)'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/htmlcov'

- script: |
    python setup.py sdist bdist_wheel
  displayName: 'Build the python distribution from source'

- task: TwineAuthenticate@1
  displayName: 'Twine Authenticate'
  inputs:
    pythonUploadServiceConnection: ljohnston

- script: |
    python -m twine upload -r nitdms --config-file $(PYPIRC_PATH) dist/*
  displayName: 'Upload to PyPI'